### PR TITLE
Upgrade to React 18

### PR DESCRIPTION
**Pull request by sehilyi**
## Description

> What was changed in this pull request?

- Apply changes in https://github.com/higlass/higlass/pull/1104 based on the current `develop` branch. (Since recent changes on the base branch led to massive conflicts, I instead newly created this branch).
  - [pkerpedjiev](https://github.com/pkerpedjiev)'s original comment:
    - Update React to react 18
    - Change hglib.viewer() function to return a promise rather than an object. This is necessary because the React component render isn't necessarily synchronous and we may not have a reference to it immediately. We'll likely have to bump the major version number of the library.

- Added documentation about upgrading React 18 under `Troubleshooting`. Feel free to suggest/make changes.
- Changed all React tests (use `await`)

> Why is it necessary?

Fixes #___

## Checklist

- [ ] Set proper GitHub labels (e.g. v1.6+, ignore if you don't know)
- [x] Unit tests added or updated
- [x] Documentation added or updated
- [ ] Example(s) added or updated
- [ ] Update schema.json if there are changes to the viewconf JSON structure format
- [ ] Screenshot for visual changes (e.g. new tracks or UI changes)
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by sehilyi** [comment]
I see we have `@wojtekmaj/enzyme-adapter-react-17` on the `package.json`. Any idea about using enzyme with the latest React?

**Comment by sehilyi** [comment]
Hi @pkerpedjiev, I made this PR to apply your changes on top of the current `develop` branch. Could you take a look and let me know if we need to make other changes to be able to upgrade React 18?

**Comment by pkerpedjiev** [comment]
I'm getting an error when trying to run on this branch. I'm probably doing something wrong but can't tell off the top of my head. Any ideas? cc @manzt 

```
(base) toc3~/projects/higlass(sehilyi/react-18|✚1…) % npm run start

> higlass@1.11.11 start /Users/pete/projects/higlass
> vite

/Users/pete/projects/higlass/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by manzt** [comment]
hmm what version of node are you on? this code is failing with a [protocol import](https://2ality.com/2021/12/node-protocol-imports.html).

**Pull request closed without merging**
