### PR TITLE
Mccalluc/example tracktypes

### PR DESCRIPTION
**Pull request by mccalluc**
## Description

What was changed in this pull request?
- Generate the html with one script rather than one-liners
- List the track types used in every viewconf example

screen shot 2018-11-26 at 9 41 37 pm

Why is it necessary?
- I want to get examples of every track type (#422) and a prerequisite to that is understanding what tracktype examples we already have. 
- and in the other direction, we would like to be able to point the users to examples of each track type.

Maybe down the road some sort of grid would be more clear visually.
Also might consider confirming in travis that this is up-to-date.

## Checklist

- [ ] Unit tests added or updated
- [ ] Documentation added or updated
- [ ] Example added or updated
- [x] Screenshot for visual changes (e.g. new tracks)
- [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by mccalluc** [comment]
(Sorry about all the commits: I'll try to rebase this and see if that helps.)

**Comment by pkerpedjiev** [comment]
You can also just squash and merge your commits. Just click on the drop down next to "Merge pull request" and select "Squash and merge".

**Comment by mccalluc** [comment]
> You can also just squash and merge your commits. Just click on the drop down next to "Merge pull request" and select "Squash and merge".

Sure: That's what I usually do with my PRs. I guess I meant to apologize for making this PR harder to review by including the earlier commits, but the end result when it is merged is the same.

> Would you mind making this a proper python string with a main function and a usage tag?

Will do.

**Comment by mccalluc** [comment]
@pkerpedjiev : ok now?

**Comment by mccalluc** [comment]
(Sent follow up questions on slack... will go ahead and merge.)

**Pull request merged**
