### PR TITLE
chore: run updated formatting & linting config

### PR DESCRIPTION
**Pull request by manzt**
## Description

Prettier had not been enforced or run for some time. This PR runs prettier, fixing CI. We could add a [`.git-blame-ignore-revs`](https://akrabat.com/ignoring-revisions-with-git-blame/) for this commit to hide the commit from git blame history.

> What was changed in this pull request?

Ran `npm run format`.

> Why is it necessary?

Fixes CI 

## Checklist

- [ ] Set proper GitHub labels (e.g. v1.6+, ignore if you don't know)
- [ ] Unit tests added or updated
- [ ] Documentation added or updated
- [ ] Example(s) added or updated
- [ ] Update schema.json if there are changes to the viewconf JSON structure format
- [ ] Screenshot for visual changes (e.g. new tracks or UI changes)
- [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by manzt** [comment]
`lint-staged` and `husky` are also no longer necessary, and I can remove them in this PR if desired.

**Comment by pkerpedjiev** [comment]
Yes on both `.git-blame-ignore-revs` and removing `lint-staged` and `husky`.

Do you know why GitHub actions complains about the curly braces?

image

**Comment by manzt** [comment]
> Do you know why GitHub actions complains about the curly braces?

This is from `eslint`, rule: `react/jsx-curly-brace-presence`. I'm also going to run `npm run lint -- --fix` which should remove lots of these warnings as well.

**Comment by manzt** [comment]
hmm, seems like there are some conflicting rules for prettier and eslint. i'll fix

**Comment by manzt** [comment]
@pkerpedjiev realizing this PR is necessary for CI to start working on outstanding PRs (linting is failing bc we haven't run prettier). Ok with a final review, then I'll merge and open a second PR adding [`.git-blame-ignore-revs`](https://akrabat.com/ignoring-revisions-with-git-blame/)  with the squashed commit hash?

**Comment by manzt** [comment]
@pkerpedjiev Ok, I squashed the prettier commits together and added `.git-blame-ignore-revs` entry for the squashed commit. When ready, we should merge this per (without squashing).

**Comment by manzt** [comment]
@alexander-veit This PR fixes the linting/formatting so that the our CI runs the test suite. I just rebased this branch on `develop`, and as you can see the tests are all passing here. Should be ready for a release either before or after this branch is merged.

**Review by alexander-veit — APPROVED** [review]

**Comment by manzt** [comment]
Oh, well non-squash commits aren't enabled for this repo. I'll update the `.git-blame-ignore-revs` hash with the squashed commit for a follow up PR.

**Pull request merged**
