### PR TITLE
Remove the scope of PR branches for GitHub Actions

### PR DESCRIPTION
**Pull request by sehilyi**
## Description

> What was changed in this pull request?

```diff
 push:
    branches: [master]
  pull_request:
-    branches: [master]
```

> Why is it necessary?

This update will trigger GitHub actions on any PR so that we can see if tests are passing before we determine to merge the PR.

Fixes #___

## Checklist

- [ ] Set proper GitHub labels (e.g. v1.6+, ignore if you don't know)
- [ ] Unit tests added or updated
- [ ] Documentation added or updated
- [ ] Example(s) added or updated
- [ ] Update schema.json if there are changes to the viewconf JSON structure format
- [ ] Screenshot for visual changes (e.g. new tracks or UI changes)
- [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by sehilyi** [comment]
I think we can run tests in the `develop` branch as well since all changes merge into `develop` before a release:

```diff
 push:
-   branches: [master]
+   branches: [master, develop]
```

**Comment by sehilyi** [comment]
It looks tests regarding a search box are failing:

```sh
13 09 2021 19:29:33.334:ERROR [HeadlessChrome 93.0.4577 (Linux 0.0.0) | Exising genome position search box | Checks that mm9 was properly set and switches back to hg19]: Expected undefined to equal 'mm9'.
    at UserContext.eval (webpack://%5Bname%5D/../test/HiGlassComponent/existing-genome-position-search-box.js?:152:34)
13 09 2021 19:29:33.336:ERROR [HeadlessChrome 93.0.4577 (Linux 0.0.0) | Exising genome position search box | Checks that hg19 was properly]: Expected undefined to equal 'hg19'.
    at UserContext.eval (webpack://%5Bname%5D/../test/HiGlassComponent/existing-genome-position-search-box.js?:162:34)
...
13 09 2021 19:29:35.902:ERROR [Chrome 93.0.4577 (Linux 0.0.0) | Exising genome position search box | Checks that mm9 was properly set and switches back to hg19]: Expected undefined to equal 'mm9'.
    at UserContext.eval (webpack://%5Bname%5D/../test/HiGlassComponent/existing-genome-position-search-box.js?:152:34)
13 09 2021 19:29:35.904:ERROR [Chrome 93.0.4577 (Linux 0.0.0) | Exising genome position search box | Checks that hg19 was properly]: Expected undefined to equal 'hg19'.
```

**Comment by pkerpedjiev** [comment]
This is good to have! I'll have to take a look at those failing tests. They're probably related to the recent PR that removed react-bootstrap from that component.

**Comment by pkerpedjiev** [comment]
Fixed and merging!

**Pull request merged**
