### PR TITLE
Vertical zooming on bedlike tracks

### PR DESCRIPTION
**Pull request by pkerpedjiev**
## Description

> What was changed in this pull request?

- Added support for vertical zooming of BedLike annotations
- Also fixes zooming and panning on mobile

> Why is it necessary?

- So that we can zoom in on regions of tightly clustered annotations

Screengrab:

Mar-17-2020 12-01-39

Fixes #___

## Checklist

- [x] Set proper GitHub labels (e.g. v1.6+, ignore if you don't know)
- [x] Unit tests added or updated
- [o] Documentation added or updated
- [o] Example(s) added or updated
- [o] Update schema.json if there are changes to the viewconf JSON structure format
- [x] Screenshot for visual changes (e.g. new tracks or UI changes)
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by alexander-veit** [comment]
Can you post a view conf where I can try this? The one in the test can't be easily copied.

**Comment by keller-mark** [comment]
It works locally. I did not try on a mobile/touch screen but it looks like that should be fixed as well

@alexander-veit to convert from the more loose js object syntax to the more strict json syntax I usually just copy and paste into one of these web-based json formatting tools https://jsonformatter.curiousconcept.com/ and then paste that output into the higlass view config

**Comment by pkerpedjiev-zymergen** [comment]
Thank you both!

@alexander-veit, here's a viewconf:

http://higlass.io/l/?d=dTfs-Jo4S5KZtzEt2jlJGA

**Comment by pkerpedjiev** [comment]
Going to merge for now. Future bug fixes will go in subsequent PRs. Thanks for the reviews!

**Pull request merged**
