### PR TITLE
Start breaking up tests

### PR DESCRIPTION
**Pull request by pkerpedjiev**
## Description

> What was changed in this pull request?

- Started breaking up the HiGlassComponentTests into smaller units
- The use of the fetch mocker is still very limited pending more testing
- The vast majority of the changes in this PR are either splitting up the tests in HiGlassComponentTests into individual files or linting changes

> Why is it necessary?

- Splitting up the tests in HiGlassComponentTests will help us more easily identify and fix failures

Fixes #___

## Checklist

- [ ] Set proper GitHub labels (e.g. v1.6+, ignore if you don't know)
- [x] Unit tests added or updated
- [ ] Documentation added or updated
- [ ] Example(s) added or updated
- [ ] Update schema.json if there are changes to the viewconf JSON structure format
- [ ] Screenshot for visual changes (e.g. new tracks or UI changes)
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by alexander-veit** [comment]
Are the tests working for you locally? I have the same problems with them, as I had a few months ago. Sometimes they work, sometimes a random tests throws
`Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

**Comment by alexander-veit** [comment]
Also, do you know why the tests that you disabled are causing issues?

**Review by alexander-veit — APPROVED** [review]
I thinks that's ok. It is hard to tell with all these formatting changes.
Please note that some tests have the fetch-mocker enabled, but your are not submitting the mocked responses. That still works, since the fetch-mocker will just go to the server in this case. I just wanted to mention it, in case you wanted to disable it everywhere.
Minor thing: `'test/SchemaTests.js',` in `karma.conf.js` does not exists.

**Comment by pkerpedjiev** [comment]
Hey Alex,

Thanks for looking.

>Are the tests working for you locally?

Yeah. 

> Also, do you know why the tests that you disabled are causing issues?

Unfortunately not. But since this PR doesn't change any functionality, those breaking issues should be in the code base already. I think it's better to get the tests running and then focus on fixing things rather than trying to get everything running again.

> Please note that some tests have the fetch-mocker enabled, but your are not submitting the mocked responses. That still works, since the fetch-mocker will just go to the server in this case. I just wanted to mention it, in case you wanted to disable it everywhere.

I think this is OK. We can add those mocked responses as we go along.

>  Minor thing: 'test/SchemaTests.js', in karma.conf.js does not exists.

Good catch. All remove it from karma.conf.js before merging 👍

**Pull request merged**
