### PR TITLE
Allow K/M shortcuts when entering genomic coordinates in searchbox

### LINKED ISSUE #838: Allow for K/M shortcuts when entring genomic coordinates in searchbox
Right now, if you often enter coordinates in the searchbox, you have to enter a lot of zeros ("chr1:150000000-155000000"). Would be very nice to be able to just use "chr1:150M-155M".

### PR DESCRIPTION
**Pull request by sehilyi**
## Description

> What was changed in this pull request?

Minor updates on allowing K/M shortcuts when entering genomic coordinates in searchbox (e.g., "chr1:150M-155M").

> Why is it necessary?

It would be easier to use K and M shortcuts when you need to enter a lot of zeros ("chr1:150000000-155000000").

Fixes #838

## Checklist

- [ ] Set proper GitHub labels (e.g. v1.6+, ignore if you don't know)
- [x] Unit tests added or updated
- [x] Documentation added or updated
- [ ] Example(s) added or updated
- [ ] Update schema.json if there are changes to the viewconf JSON structure format
- [ ] Screenshot for visual changes (e.g. new tracks or UI changes)
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by pkerpedjiev** [comment]
This looks really helpful to have! Not sure if you were done with it or not but if you wouldn't mind updating the docs and adding a test or two, that would be really helpful.

**Comment by sehilyi** [comment]
Sure! I've just added tests and updated the docs.

**Comment by sehilyi** [comment]
Oh! I see. I just updated the `views.rst` documentation and also changed the function name to `convertNumberNotation`. Thanks for letting me know the issue.

**Comment by pkerpedjiev** [comment]
I just thought of a potential issue. What if someone enters `1.5M`. Wouldn't this result in the value being converted to `1.5000000` using your method?

**Comment by sehilyi** [comment]
Based on your comment, I updated the function to take diverse cases of using the `K & M` notations. Now the following cases convert well:

- 1.5M to 1500000
- 1.50M to 1500000
- 0.05M to 50000
- 0.050M to 50000
- "ABCM" to "ABCM" (Invalid numbers are returned as they are)

I added some additional tests for this.

**Comment by pkerpedjiev** [comment]
image

**Pull request merged**
