### PR TITLE
[Incomplete] Added option to render axes without scientific notation

### PR DESCRIPTION
**Pull request by pkerpedjiev**
## Description

What was changed in this pull request?

I added the `axisLabelFormatting` option to 1d quantitative tracks ('horizontal-line', 'horizontal-bar', 'horizontal-point' and the their vertical counterparts). This option lets you specify `normal` or `scientific` and alters how the axis is rendered:

image

Why is it necessary?

Some people like scientific notation, others don't.

## Checklist

- [x] Unit tests added or updated
- [ ] Documentation added or updated
- [x] Example added or updated
    - http://higlass.io/app/?config=R-oOO7ohTgaqByNuD7X4-g
- [x] Screenshot for visual changes (e.g. new tracks)

### CODE REVIEW

**Comment by flekschas** [comment]
Looks good so far. Would this change the default behavior?

**Comment by pkerpedjiev** [comment]
No, the default remains scientific notation.

**Comment by pkerpedjiev** [comment]
Fuck. I merged it without adding documentation.

**Comment by pkerpedjiev** [comment]
I'll add it in separate PR that will include a bunch of documentation updates.

**Pull request merged**
