### PR TITLE
Add troubleshooting section to docs

### PR DESCRIPTION
**Pull request by Phlya**
Created `troubleshooting.rst` in docs.

Added there how to fix empty page on FF on Linux.

- [ ] Set proper GitHub labels (e.g. v1.6+, ignore if you don't know)
- [ ] Unit tests added or updated
- [x] Documentation added or updated
- [ ] Example(s) added or updated
- [ ] Update schema.json if there are changes to the viewconf JSON structure format
- [ ] Screenshot for visual changes (e.g. new tracks or UI changes)
- [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by pkerpedjiev** [comment]
Thanks Ilya!

The only change I'd suggest is to make the second level heading more generic so that the sidebar remains clean. Something like:

```
===========
  Troubleshooting
  ===========

  Empty Page
  ==========

  HiGlass showing as an empty page in Firefox on Linux
  ----------------------------------------------------

  Due to a bug in Mesa video drivers that has since been fixed, Firefox introduced a workaround which prevents HiGlass to load.
  To disable this workaround, set ``gfx.work-around-driver-bugs=false`` in ``about:config``, and restart the browser.

  Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1601682
```

**Comment by Phlya** [comment]
Won't this make `Troubleshooting` and `Empty page` be on the same level in the hierarchy? Is that what you want?..

**Comment by pkerpedjiev** [comment]
Nope

image

**Comment by Phlya** [comment]
Right, yeah.

`Empty page` and ` HiGlass showing as an empty page in Firefox on Linux` look the same on GitHub though
image

**Comment by pkerpedjiev** [comment]
That's OK. Google results will point to the docs page rather than the Github source so I'm not too concerned about that.

**Comment by Phlya** [comment]
OK, so it's rendered correctly in docs? Cool.

**Comment by pkerpedjiev** [comment]
Good enough :-)

image

**Pull request merged**
