### PR TITLE
Flekschas/export rendered view as png

### PR DESCRIPTION
**Pull request by flekschas**
## Description

> What was changed in this pull request?

When exporting a view as PNG, the actual rendered view is now exported. Previously the SVG rendering was exported as a PNG but the SVG export isn't 100% the same as the rendered view in the browser.

> Why is it necessary?

To simplify the export and export the actually visible views

## Checklist

- ~[ ] Unit tests added or updated~
- ~[ ] Documentation added or updated~
- ~[ ] Example added or updated~
- ~[ ] Screenshot for visual changes (e.g. new tracks)~
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by pkerpedjiev** [comment]
Ohhhh... the reason it was exporting the SVG output is that we can have SVG tracks that are rendered independent of PIXI.

Probably better to keep the SVG-based export. Sorry for not realizing that earlier,

**Comment by flekschas** [comment]
Oh shoot that's true. Too bad because it looked like this PR fixed #652. Maybe there's another way to just render the current SVG on top to avoid having to re-export everything as SVG.

**Comment by pkerpedjiev** [comment]
Is it possible to fix #652 without jumping to using the rendered view to to export?

**Comment by flekschas** [comment]
Probably but I don’t know how from the top of my head :)

**Pull request closed without merging**
