### PR TITLE
Add link to slack on README

### PR DESCRIPTION
**Pull request by mccalluc**
This was suggested during the meeting today. This is one way to do it; there are others. [skip ci]

### CODE REVIEW

**Comment by flekschas** [comment]
@mccalluc Do you know if we could use this: https://github.com/gliderlabs/slack/blob/master/slackin/README.md#svg

**Comment by mccalluc** [comment]
@flekschas : Sure.

**Comment by flekschas** [comment]
Cool thanks!

**Comment by flekschas** [comment]
(I think TravisCI just needs a restart)

**Comment by mccalluc** [comment]
(I meant to skip-ci this, but I've just restarted travis, if that's a concern.)

**Pull request merged**
